// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASUA8ofJxrRKgco7pa9W0NqtveffGGMcA',
    appId: '1:588141268514:web:4e2fc0e3726e87aec3847b',
    messagingSenderId: '588141268514',
    projectId: 'whatahoot2-71b79',
    authDomain: 'whatahoot2-71b79.firebaseapp.com',
    storageBucket: 'whatahoot2-71b79.appspot.com',
    measurementId: 'G-K2M708LGN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSOzN-HhR0ysFb_irv4_CCnCvGhNfp5gY',
    appId: '1:588141268514:android:7909624d74b9deb2c3847b',
    messagingSenderId: '588141268514',
    projectId: 'whatahoot2-71b79',
    storageBucket: 'whatahoot2-71b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekiNziiU3L5mvdkBf9_t_tdzdCIrUp2A',
    appId: '1:588141268514:ios:db6ce7e4d52d8928c3847b',
    messagingSenderId: '588141268514',
    projectId: 'whatahoot2-71b79',
    storageBucket: 'whatahoot2-71b79.appspot.com',
    iosBundleId: 'com.example.whatahoot2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCekiNziiU3L5mvdkBf9_t_tdzdCIrUp2A',
    appId: '1:588141268514:ios:52ca5a5c5d0f7182c3847b',
    messagingSenderId: '588141268514',
    projectId: 'whatahoot2-71b79',
    storageBucket: 'whatahoot2-71b79.appspot.com',
    iosBundleId: 'com.example.whatahoot2.RunnerTests',
  );
}
